// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using EasyAbp.Abp.SettingUi;
using System.Collections.Generic;
using EasyAbp.Abp.SettingUi.Dto;

// ReSharper disable once CheckNamespace
namespace EasyAbp.Abp.SettingUi.ClientProxies
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(ISettingUiAppService), typeof(SettingUiClientProxy))]
    public partial class SettingUiClientProxy : ClientProxyBase<ISettingUiAppService>, ISettingUiAppService
    {
        public virtual async Task<List<SettingGroup>> GroupSettingDefinitionsAsync()
        {
            return await RequestAsync<List<SettingGroup>>(nameof(GroupSettingDefinitionsAsync));
        }

        public virtual async Task SetSettingValuesAsync(Dictionary<String,String> settingValues)
        {
            await RequestAsync(nameof(SetSettingValuesAsync), new ClientProxyRequestTypeValue
            {
                { typeof(Dictionary<String,String>), settingValues }
            });
        }

        public virtual async Task ResetSettingValuesAsync(List<String> settingNames)
        {
            await RequestAsync(nameof(ResetSettingValuesAsync), new ClientProxyRequestTypeValue
            {
                { typeof(List<String>), settingNames }
            });
        }
    }
}
